### ISSUE TITLE
heads up: updated topic summary data

### ISSUE THREAD

**Issue by jerry-appliedAIstudio** [nervecentergarage/structured-journalism-content-templates#3]
i updated the snippet summary with labels that match what shows in the topic details

**Comment by lrwilt** [comment]
Are you talking about the primary and secondary labels? If so, I see them and we can close this.

**Comment by jerry-appliedAIstudio** [comment]
no, i'm talking about changing the labels from things like "videos" to "video"

**Comment by lrwilt** [comment]
I see that now. My file version was behind.
